// <auto-generated />
using System;
using Laraue.Apps.StructuredMessages.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laraue.Apps.StructuredMessages.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260522170219_RenamePersonalOrganizations")]
    partial class RenamePersonalOrganizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.DirectEpicPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("ChildrenIssuesAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("children_issues_access_level");

                    b.Property<byte>("EntityAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("entity_access_level");

                    b.Property<long>("EpicId")
                        .HasColumnType("bigint")
                        .HasColumnName("epic_id");

                    b.Property<long>("OrganizationUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_user_id");

                    b.HasKey("Id")
                        .HasName("pk_direct_epic_permissions");

                    b.HasIndex("EpicId")
                        .HasDatabaseName("ix_direct_epic_permissions_epic_id");

                    b.HasIndex("OrganizationUserId")
                        .HasDatabaseName("ix_direct_epic_permissions_organization_user_id");

                    b.ToTable("direct_epic_permissions", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.DirectSpacePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("ChildrenEpicsAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("children_epics_access_level");

                    b.Property<byte>("ChildrenIssuesAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("children_issues_access_level");

                    b.Property<byte>("EntityAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("entity_access_level");

                    b.Property<long>("OrganizationUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_user_id");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("pk_direct_space_permissions");

                    b.HasIndex("OrganizationUserId")
                        .HasDatabaseName("ix_direct_space_permissions_organization_user_id");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_direct_space_permissions_space_id");

                    b.ToTable("direct_space_permissions", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Epic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("space_id");

                    b.Property<DateTime>("TouchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("touched_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_epics");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_epics_space_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_epics_user_id");

                    b.ToTable("epics", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("status_id");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_message_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("Content")
                        .HasDatabaseName("ix_issues_content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Content"), new[] { "gin_trgm_ops" });

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_issues_status_id");

                    b.HasIndex("TelegramMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_telegram_message_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_issues_user_id");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("JoinCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("SlugPostfix")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("slug_postfix");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_join_code");

                    b.HasIndex("OwnerId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_owner_id_type")
                        .HasFilter("type = 1");

                    b.HasIndex("SlugPostfix", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug_postfix_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.OrganizationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("AdminAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("admin_access_level");

                    b.Property<byte>("EpicsAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("epics_access_level");

                    b.Property<byte>("IssuesAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("issues_access_level");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<byte>("SpacesAccessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("spaces_access_level");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_users");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_users_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_users_user_id");

                    b.ToTable("organization_users", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Space", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_spaces");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_spaces_creator_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_spaces_organization_id");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<long>("EpicId")
                        .HasColumnType("bigint")
                        .HasColumnName("epic_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_statuses");

                    b.HasIndex("EpicId")
                        .HasDatabaseName("ix_statuses_epic_id");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_id");

                    b.Property<string>("FileUniqueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_unique_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_telegram_files");

                    b.HasIndex("FileUniqueId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_files_file_unique_id");

                    b.ToTable("telegram_files", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMediaGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_media_groups");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_media_groups_external_id");

                    b.ToTable("telegram_media_groups", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExternalChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_chat_id");

                    b.Property<int>("ExternalMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("external_message_id");

                    b.Property<long?>("TelegramMediaGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_media_group_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_messages");

                    b.HasIndex("TelegramMediaGroupId")
                        .HasDatabaseName("ix_telegram_messages_telegram_media_group_id");

                    b.HasIndex("ExternalMessageId", "ExternalChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_messages_external_message_id_external_chat_id");

                    b.ToTable("telegram_messages", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessagePhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("PhotoType")
                        .HasColumnType("integer")
                        .HasColumnName("photo_type");

                    b.Property<Guid>("TelegramFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("telegram_file_id");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_message_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_telegram_photos");

                    b.HasIndex("TelegramFileId")
                        .HasDatabaseName("ix_telegram_photos_telegram_file_id");

                    b.HasIndex("TelegramMessageId")
                        .HasDatabaseName("ix_telegram_photos_telegram_message_id");

                    b.ToTable("telegram_photos", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessageVideo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_message_id");

                    b.Property<Guid?>("ThumbnailFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_file_id");

                    b.Property<int?>("ThumbnailHeight")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_height");

                    b.Property<int?>("ThumbnailWidth")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_width");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_telegram_videos");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_telegram_videos_file_id");

                    b.HasIndex("TelegramMessageId")
                        .HasDatabaseName("ix_telegram_videos_telegram_message_id");

                    b.HasIndex("ThumbnailFileId")
                        .HasDatabaseName("ix_telegram_videos_thumbnail_file_id");

                    b.ToTable("telegram_videos", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TelegramFirstName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_first_name");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramLanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("telegram_language_code");

                    b.Property<string>("TelegramLastName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_last_name");

                    b.Property<string>("TelegramUserName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.UserOrganizationPreferences", b =>
                {
                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long?>("SelectedSpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("selected_space_id");

                    b.HasKey("OrganizationId", "UserId")
                        .HasName("pk_user_organization_preferences");

                    b.ToTable("user_organization_preferences", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("EpicSortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("epic_sort_order");

                    b.HasKey("UserId")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.Interceptors.EFCore.InterceptorStateModel<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ActiveInterceptor")
                        .HasColumnType("text")
                        .HasColumnName("active_interceptor");

                    b.Property<string>("InterceptorContext")
                        .HasColumnType("text")
                        .HasColumnName("interceptor_context");

                    b.HasKey("UserId")
                        .HasName("pk_interceptor_state");

                    b.ToTable("interceptor_state", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.FailedUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_failed_updates");

                    b.ToTable("failed_updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.Update", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.HasKey("Id")
                        .HasName("pk_updates");

                    b.ToTable("updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.DirectEpicPermission", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Epic", "Epic")
                        .WithMany("Users")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direct_epic_permissions_epics_epic_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.OrganizationUser", "OrganizationUser")
                        .WithMany()
                        .HasForeignKey("OrganizationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direct_epic_permissions_organization_users_organization_use");

                    b.Navigation("Epic");

                    b.Navigation("OrganizationUser");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.DirectSpacePermission", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.OrganizationUser", "OrganizationUser")
                        .WithMany()
                        .HasForeignKey("OrganizationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direct_space_permissions_organization_users_organization_us");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Space", "Space")
                        .WithMany("Users")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direct_space_permissions_spaces_space_id");

                    b.Navigation("OrganizationUser");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Epic", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Space", "Space")
                        .WithMany("Epics")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epics_spaces_space_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany("Epics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epics_users_user_id");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Issue", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Status", "Status")
                        .WithMany("Issues")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_statuses_status_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", "TelegramMessage")
                        .WithOne("Issue")
                        .HasForeignKey("Laraue.Apps.StructuredMessages.DataAccess.Models.Issue", "TelegramMessageId")
                        .HasConstraintName("fk_issues_telegram_messages_telegram_message_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_users_user_id");

                    b.Navigation("Status");

                    b.Navigation("TelegramMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Organization", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "Owner")
                        .WithMany("Organizations")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.OrganizationUser", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_organizations_organization_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_users_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Space", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "Creator")
                        .WithMany("Spaces")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_users_creator_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Organization", "Organization")
                        .WithMany("Spaces")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_organizations_organization_id");

                    b.Navigation("Creator");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Status", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Epic", "Epic")
                        .WithMany("Statuses")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_statuses_epics_epic_id");

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMediaGroup", "TelegramMediaGroup")
                        .WithMany()
                        .HasForeignKey("TelegramMediaGroupId")
                        .HasConstraintName("fk_telegram_messages_telegram_media_groups_telegram_media_grou");

                    b.Navigation("TelegramMediaGroup");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessagePhoto", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "File")
                        .WithMany()
                        .HasForeignKey("TelegramFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_photos_telegram_files_telegram_file_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", "TelegramMessage")
                        .WithMany()
                        .HasForeignKey("TelegramMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_photos_telegram_messages_telegram_message_id");

                    b.Navigation("File");

                    b.Navigation("TelegramMessage");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessageVideo", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_videos_telegram_files_file_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", "TelegramMessage")
                        .WithMany()
                        .HasForeignKey("TelegramMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_videos_telegram_messages_telegram_message_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "ThumbnailFile")
                        .WithMany()
                        .HasForeignKey("ThumbnailFileId")
                        .HasConstraintName("fk_telegram_videos_telegram_files_thumbnail_file_id");

                    b.Navigation("File");

                    b.Navigation("TelegramMessage");

                    b.Navigation("ThumbnailFile");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Epic", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Organization", b =>
                {
                    b.Navigation("Spaces");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Space", b =>
                {
                    b.Navigation("Epics");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Status", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", b =>
                {
                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.User", b =>
                {
                    b.Navigation("Epics");

                    b.Navigation("Organizations");

                    b.Navigation("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
