// <auto-generated />
using System;
using Laraue.Apps.Boards.DataAccess;
using Laraue.Apps.StructuredMessages.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laraue.Apps.StructuredMessages.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260326085924_NewMessagesSchema")]
    partial class NewMessagesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("status_id");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_cards_category_id");

                    b.HasIndex("Content")
                        .HasDatabaseName("ix_cards_content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Content"), new[] { "gin_trgm_ops" });

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_cards_status_id");

                    b.HasIndex("TelegramMessageId")
                        .HasDatabaseName("ix_cards_telegram_message_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_cards_user_id");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.CardCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_card_categories");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_card_categories_user_id");

                    b.ToTable("card_categories", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.CardStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CardCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_category_id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_card_statuses");

                    b.HasIndex("CardCategoryId")
                        .HasDatabaseName("ix_card_statuses_card_category_id");

                    b.ToTable("card_statuses", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageTelegramPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("PhotoType")
                        .HasColumnType("integer")
                        .HasColumnName("photo_type");

                    b.Property<Guid>("TelegramFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("telegram_file_id");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_telegram_photos");

                    b.HasIndex("TelegramFileId")
                        .HasDatabaseName("ix_telegram_photos_telegram_file_id");

                    b.HasIndex("TelegramMessageId")
                        .HasDatabaseName("ix_telegram_photos_telegram_message_id");

                    b.ToTable("telegram_photos", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageTelegramVideo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<Guid?>("ThumbnailFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_file_id");

                    b.Property<int?>("ThumbnailHeight")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_height");

                    b.Property<int?>("ThumbnailWidth")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_width");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_telegram_videos");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_telegram_videos_file_id");

                    b.HasIndex("TelegramMessageId")
                        .HasDatabaseName("ix_telegram_videos_telegram_message_id");

                    b.HasIndex("ThumbnailFileId")
                        .HasDatabaseName("ix_telegram_videos_thumbnail_file_id");

                    b.ToTable("telegram_videos", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_id");

                    b.Property<string>("FileUniqueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_unique_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_telegram_files");

                    b.HasIndex("FileUniqueId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_files_file_unique_id");

                    b.ToTable("telegram_files", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMediaGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_media_groups");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_media_groups_external_id");

                    b.ToTable("telegram_media_groups", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("TelegramMediaGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_media_group_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_messages");

                    b.HasIndex("TelegramMediaGroupId")
                        .HasDatabaseName("ix_telegram_messages_telegram_media_group_id");

                    b.ToTable("telegram_messages", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TelegramFirstName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_first_name");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramLanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("telegram_language_code");

                    b.Property<string>("TelegramLastName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_last_name");

                    b.Property<string>("TelegramUserName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.Interceptors.EFCore.InterceptorStateModel<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ActiveInterceptor")
                        .HasColumnType("text")
                        .HasColumnName("active_interceptor");

                    b.Property<string>("InterceptorContext")
                        .HasColumnType("text")
                        .HasColumnName("interceptor_context");

                    b.HasKey("UserId")
                        .HasName("pk_interceptor_state");

                    b.ToTable("interceptor_state", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.FailedUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_failed_updates");

                    b.ToTable("failed_updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.Update", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.HasKey("Id")
                        .HasName("pk_updates");

                    b.ToTable("updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Card", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.CardCategory", "Category")
                        .WithMany("Cards")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_cards_card_categories_category_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.CardStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .HasConstraintName("fk_cards_card_statuses_status_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", "TelegramMessage")
                        .WithOne("Card")
                        .HasForeignKey("Laraue.Apps.StructuredMessages.DataAccess.Models.Card", "TelegramMessageId")
                        .HasConstraintName("fk_cards_telegram_messages_telegram_message_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cards_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("Status");

                    b.Navigation("TelegramMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.CardCategory", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.CardStatus", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.CardCategory", "CardCategory")
                        .WithMany("Statuses")
                        .HasForeignKey("CardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_statuses_card_categories_card_category_id");

                    b.Navigation("CardCategory");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageTelegramPhoto", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "File")
                        .WithMany()
                        .HasForeignKey("TelegramFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_photos_telegram_files_telegram_file_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", "TelegramMessage")
                        .WithMany()
                        .HasForeignKey("TelegramMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_photos_telegram_messages_telegram_message_id");

                    b.Navigation("File");

                    b.Navigation("TelegramMessage");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageTelegramVideo", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_videos_telegram_files_file_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", "Message")
                        .WithMany()
                        .HasForeignKey("TelegramMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_videos_telegram_messages_telegram_message_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "ThumbnailFile")
                        .WithMany()
                        .HasForeignKey("ThumbnailFileId")
                        .HasConstraintName("fk_telegram_videos_telegram_files_thumbnail_file_id");

                    b.Navigation("File");

                    b.Navigation("Message");

                    b.Navigation("ThumbnailFile");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMediaGroup", "TelegramMediaGroup")
                        .WithMany()
                        .HasForeignKey("TelegramMediaGroupId")
                        .HasConstraintName("fk_telegram_messages_telegram_media_groups_telegram_media_grou");

                    b.Navigation("TelegramMediaGroup");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.CardCategory", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramMessage", b =>
                {
                    b.Navigation("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
