// <auto-generated />
using System;
using Laraue.Apps.Boards.DataAccess;
using Laraue.Apps.StructuredMessages.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laraue.Apps.StructuredMessages.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260321101553_MakeMimeTypeNullable")]
    partial class MakeMimeTypeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("status_id");

                    b.Property<string>("TelegramMediaGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("telegram_media_group_id");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_messages_category_id");

                    b.HasIndex("Content")
                        .HasDatabaseName("ix_messages_content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Content"), new[] { "gin_trgm_ops" });

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_messages_status_id");

                    b.HasIndex("TelegramMediaGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_telegram_media_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_messages_user_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_message_categories");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_message_categories_user_id");

                    b.ToTable("message_categories", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<long>("MessageCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_message_statuses");

                    b.HasIndex("MessageCategoryId")
                        .HasDatabaseName("ix_message_statuses_message_category_id");

                    b.ToTable("message_statuses", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageTelegramPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<Guid>("TelegramFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("telegram_file_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_telegram_photos");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_telegram_photos_message_id");

                    b.HasIndex("TelegramFileId")
                        .HasDatabaseName("ix_telegram_photos_telegram_file_id");

                    b.ToTable("telegram_photos", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageTelegramVideo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("ThumbnailFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_file_id");

                    b.Property<int?>("ThumbnailHeight")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_height");

                    b.Property<int?>("ThumbnailWidth")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_width");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_telegram_videos");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_telegram_videos_file_id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_telegram_videos_message_id");

                    b.HasIndex("ThumbnailFileId")
                        .HasDatabaseName("ix_telegram_videos_thumbnail_file_id");

                    b.ToTable("telegram_videos", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_id");

                    b.Property<string>("FileUniqueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_unique_id");

                    b.Property<string>("MimeType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_telegram_files");

                    b.HasIndex("FileUniqueId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_files_file_unique_id");

                    b.ToTable("telegram_files", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TelegramFirstName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_first_name");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramLanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("telegram_language_code");

                    b.Property<string>("TelegramLastName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_last_name");

                    b.Property<string>("TelegramUserName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.Interceptors.EFCore.InterceptorStateModel<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ActiveInterceptor")
                        .HasColumnType("text")
                        .HasColumnName("active_interceptor");

                    b.Property<string>("InterceptorContext")
                        .HasColumnType("text")
                        .HasColumnName("interceptor_context");

                    b.HasKey("UserId")
                        .HasName("pk_interceptor_state");

                    b.ToTable("interceptor_state", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.FailedUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_failed_updates");

                    b.ToTable("failed_updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.Update", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.HasKey("Id")
                        .HasName("pk_updates");

                    b.ToTable("updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Message", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", "Category")
                        .WithMany("Messages")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_messages_message_categories_category_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .HasConstraintName("fk_messages_message_statuses_status_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageStatus", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", "MessageCategory")
                        .WithMany("Statuses")
                        .HasForeignKey("MessageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_statuses_message_categories_message_category_id");

                    b.Navigation("MessageCategory");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageTelegramPhoto", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Message", "Message")
                        .WithMany("Photos")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_photos_messages_message_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "File")
                        .WithMany()
                        .HasForeignKey("TelegramFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_photos_telegram_files_telegram_file_id");

                    b.Navigation("File");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageTelegramVideo", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_videos_telegram_files_file_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.Message", "Message")
                        .WithMany("Videos")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_videos_messages_message_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.TelegramFile", "ThumbnailFile")
                        .WithMany()
                        .HasForeignKey("ThumbnailFileId")
                        .HasConstraintName("fk_telegram_videos_telegram_files_thumbnail_file_id");

                    b.Navigation("File");

                    b.Navigation("Message");

                    b.Navigation("ThumbnailFile");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Message", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
