// <auto-generated />
using System;
using Laraue.Apps.Boards.DataAccess;
using Laraue.Apps.StructuredMessages.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laraue.Apps.StructuredMessages.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260307065148_AddInterceptorsTable")]
    partial class AddInterceptorsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("MessageTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_type_id");

                    b.Property<long?>("MessageTypeStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_type_status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("MessageTypeId")
                        .HasDatabaseName("ix_messages_message_type_id");

                    b.HasIndex("MessageTypeStatusId")
                        .HasDatabaseName("ix_messages_message_type_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_messages_user_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_message_types");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_message_types_user_id");

                    b.ToTable("message_types", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategoryStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<long>("MessageCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_message_type_statuses");

                    b.HasIndex("MessageCategoryId")
                        .HasDatabaseName("ix_message_type_statuses_message_category_id");

                    b.ToTable("message_type_statuses", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramLanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("telegram_language_code");

                    b.Property<string>("TelegramUserName")
                        .HasColumnType("text")
                        .HasColumnName("telegram_user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.Interceptors.EFCore.InterceptorStateModel<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ActiveInterceptor")
                        .HasColumnType("text")
                        .HasColumnName("active_interceptor");

                    b.Property<string>("InterceptorContext")
                        .HasColumnType("text")
                        .HasColumnName("interceptor_context");

                    b.HasKey("UserId")
                        .HasName("pk_interceptor_state");

                    b.ToTable("interceptor_state", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.FailedUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_failed_updates");

                    b.ToTable("failed_updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Telegram.NET.UpdatesQueue.EFCore.DataAccess.Update", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.HasKey("Id")
                        .HasName("pk_updates");

                    b.ToTable("updates", (string)null);
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.Message", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", "MessageType")
                        .WithMany()
                        .HasForeignKey("MessageTypeId")
                        .HasConstraintName("fk_messages_message_types_message_type_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategoryStatus", "MessageTypeStatus")
                        .WithMany()
                        .HasForeignKey("MessageTypeStatusId")
                        .HasConstraintName("fk_messages_message_type_statuses_message_type_status_id");

                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_user_id");

                    b.Navigation("MessageType");

                    b.Navigation("MessageTypeStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_types_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategoryStatus", b =>
                {
                    b.HasOne("Laraue.Apps.StructuredMessages.DataAccess.Models.MessageCategory", "MessageCategory")
                        .WithMany()
                        .HasForeignKey("MessageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_type_statuses_message_types_message_category_id");

                    b.Navigation("MessageCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
